baseURL = "https://xirage.github.io/OpenSource-Kompass/"
languageCode = "de-de"
title = "OpenSource-Kompass"          # z.B. "Problemloeser" o.ä. - hier anpassen
theme = "PaperMod"
enableRobotsTXT = true

[params]
  description = "Notizen und Lessons Learned zu Software, DIY-Projekten und Entscheidungen."
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = false
  defaultTheme = "auto"          # hell/dunkel automatisch je nach Systemeinstellung

#[[menu.main]]
#  name = "Start"
#  url = "/"
#  weight = 1

#[[menu.main]]
#  name = "Alle Beiträge"
#  url = "/posts/"
#  weight = 2

[taxonomies]
  category = "categories"
  tag = "tags"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4