baseURL = "https://xirage.github.io/OpenSource-Kompass/"
languageCode = "de-de"
title = "OpenSource-Kompass"          # z.B. "Problemloeser" o.ä. - hier anpassen
theme = "PaperMod"
enableRobotsTXT = true

[params]
  homeInfoParams.Title = "OpenSource-Kompass"
  homeInfoParams.Content = """
## Einleitung

Meiner Meinung nach ist das Internet, Programme und Apps aktuell ziemlich weit von dem Grundgedanke, den es früher hatte, entfernt. Einer Demokratisierung der Kommunikation. Aktuell werden die meisten Apps von großen Unternehmen mit fragwürdigen Interessen beherrscht. Open Source bietet dazu eine Gegenbewegung an. Mittlerweile gibt es auch sehr viele Programme/Apps, die sehr gut funktionieren und manchmal sogar besser sind als ihre Closed-Source-Alternativen. Ich will mit dieser Seite einen kleinen Beitrag zur Verbreitung von Open-Source-Apps leisten. Dabei ist sehr viel subjektiv, und andere finden manche Apps vielleicht weniger oder mehr nützlich. Trotzdem möchte ich hier meine subjektive Meinung darstellen und vielleicht dem ein oder anderen Inspiration zu neuen Apps geben. Sie ist offensichtlich nicht vollständig, und bei vielen Sachen kenne ich Alternativen und bessere Dinge leider nicht – deshalb seht mir das nach und schreibt mir gerne eine Mail, wenn ihr noch weitere coole Ideen habt.

## How to navigieren

Im Folgenden teile ich es in Handy und PC/Laptop auf. Das sollte so das meiste für den Otto-Normal-Verbraucher abdecken. Ich habe dann versucht, die großen/wichtigen Funktionalitäten abzudecken (Betriebssystem, Browser, Navigation, ...).

Ich habe die Apps und Programme immer in drei Kategorien eingeteilt, womit man ungefähr einschätzen kann, wie gut die App/das Programm ist. Falls eine App mal nicht Open Source ist, erwähne ich das explizit. Alle ohne Info sind Open Source:

1. Genauso gut oder besser wie Closed Source
2. Leichte Einbußen, aber immer noch auf Closed Source verzichtbar
3. Guter Anfang, aber Closed Source für einige Anwendungen unverzichtbar
"""

#[[menu.main]]
#  name = "Start"
#  url = "/"
#  weight = 1

#[[menu.main]]
#  name = "Alle Beiträge"
#  url = "/posts/"
#  weight = 2

[taxonomies]
  category = "categories"
  tag = "tags"